export const arrKey = [
  { value: '`', shiftValue: '~', code: 'Backquote', class: 'key' },
  { value: '1', shiftValue: '!', code: 'Digit1', class: 'key' },
  { value: '2', shiftValue: '@', code: 'Digit2', class: 'key' },
  { value: '3', shiftValue: '#', code: 'Digit3', class: 'key' },
  { value: '4', shiftValue: '$', code: 'Digit4', class: 'key' },
  { value: '5', shiftValue: '%', code: 'Digit5', class: 'key' },
  { value: '6', shiftValue: '^', code: 'Digit6', class: 'key' },
  { value: '7', shiftValue: '&', code: 'Digit7', class: 'key' },
  { value: '8', shiftValue: '*', code: 'Digit8', class: 'key' },
  { value: '9', shiftValue: '(', code: 'Digit9', class: 'key' },
  { value: '0', shiftValue: ')', code: 'Digit0', class: 'key' },
  { value: '-', shiftValue: '_', code: 'Minus', class: 'key' },
  { value: '=', shiftValue: '+', code: 'Equal', class: 'key' },
  { value: 'Backspace', code: 'Backspace', class: 'backspace' },
  { value: 'Tab', code: 'Tab', class: 'tab' },
  { en: 'q', ru: 'й', code: 'KeyQ', class: 'key' },
  { en: 'w', ru: 'ц', code: 'KeyW', class: 'key' },
  { en: 'e', ru: 'у', code: 'KeyE', class: 'key' },
  { en: 'r', ru: 'к', code: 'KeyR', class: 'key' },
  { en: 't', ru: 'е', code: 'KeyT', class: 'key' },
  { en: 'y', ru: 'н', code: 'KeyY', class: 'key' },
  { en: 'u', ru: 'г', code: 'KeyU', class: 'key' },
  { en: 'i', ru: 'ш', code: 'KeyI', class: 'key' },
  { en: 'o', ru: 'щ', code: 'KeyO', class: 'key' },
  { en: 'p', ru: 'з', code: 'KeyP', class: 'key' },
  { en: '[', ru: 'х', code: 'BracketLeft', class: 'key' },
  { en: ']', ru: 'ъ', code: 'BracketRight', class: 'key' },
  { value: '\\', shiftValue: '|', code: 'Backslash', class: 'key' },
  { value: 'Del', code: 'Delete', class: 'delete' },
  { value: 'CapsLock', code: 'CapsLock', class: 'capslook' },
  { en: 'a', ru: 'ф', code: 'KeyA', class: 'key' },
  { en: 's', ru: 'ы', code: 'KeyS', class: 'key' },
  { en: 'd', ru: 'в', code: 'KeyD', class: 'key' },
  { en: 'f', ru: 'а', code: 'KeyF', class: 'key' },
  { en: 'g', ru: 'п', code: 'KeyG', class: 'key' },
  { en: 'h', ru: 'р', code: 'KeyH', class: 'key' },
  { en: 'j', ru: 'о', code: 'KeyJ', class: 'key' },
  { en: 'k', ru: 'л', code: 'KeyK', class: 'key' },
  { en: 'l', ru: 'д', code: 'KeyL', class: 'key' },
  { en: ';', ru: 'ж', code: 'Semicolon', class: 'key' },
  { en: '\'', ru: 'э', code: 'Quote', class: 'key' },
  { value: 'Enter', code: 'Enter', class: 'enter' },
  { value: 'Shift', code: 'ShiftLeft', class: 'shift' },
  { en: 'z', ru: 'я', code: 'KeyZ', class: 'key' },
  { en: 'x', ru: 'ч', code: 'KeyX', class: 'key' },
  { en: 'c', ru: 'с', code: 'KeyC', class: 'key' },
  { en: 'v', ru: 'м', code: 'KeyV', class: 'key' },
  { en: 'b', ru: 'и', code: 'KeyB', class: 'key' },
  { en: 'n', ru: 'т', code: 'KeyN', class: 'key' },
  { en: 'm', ru: 'ь', code: 'KeyM', class: 'key' },
  { en: ',', ru: 'б', code: 'Comma', class: 'key' },
  { en: '.', ru: 'ю', code: 'Period', class: 'key' },
  { value: '/', ru: '.', shiftValue: '?', code: 'Slash', class: 'key' },
  { value: '▲', code: 'ArrowUp', class: 'key' },
  { value: 'Shift', code: 'ShiftRight', class: 'shiftR' },
  { value: 'Ctrl', code: 'ControlLeft', class: 'ctrl' },
  { value: 'WIN', code: 'MetaLeft', class: 'win' },
  { value: 'Alt', code: 'AltLeft', class: 'alt' },
  { value: ' ', code: 'Space', class: 'space' },
  { value: 'Alt', code: 'AltRight', class: 'alt' },
  { value: '◄', code: 'ArrowLeft', class: 'key' },
  { value: '▼', code: 'ArrowDown', class: 'key' },
  { value: '►', code: 'ArrowRight', class: 'key' },
  { value: 'Ctrl', code: 'ControlRight', class: 'ctrl' }
];
